Issue#60
LibreHealthIO/ehr-fhir-api pull request #65
Opened 2016-10-07 08:01 UTC by Leo24

Amend "counrty" to "county"
Add functionality for saving address info

2016-10-09 19:35 UTC, kchapple requested changes

2016-10-09 19:35 UTC, kchapple commented on src/Adapters/FHIRPatientAdapter.php
> +        $line->setValue($patient->getStreet());
@Leo24 You don't add both lines here if an array is returned by getStreet()

2016-10-10 07:30 UTC, Leo24 commented on src/Adapters/FHIRPatientAdapter.php
> +        $line->setValue($patient->getStreet());
I do not fully understand you.
Do you mean, I should return only first line from array?
like this:
        $street = $patient->getStreet();
        $line->setValue($street[0]);
        $address->addLine($line);

2016-10-10 18:25 UTC, kchapple commented on src/Adapters/FHIRPatientAdapter.php
> +        $line->setValue($patient->getStreet());
@Leo24 No, The iPhone UI has two lines, address-line-1 and address-line-2. We are taking those two lines and storing them in the LibreEHR database like this "address-line-1 | address-line-2" with a "|" delimiter. When we get the address out of the LibreEHR database and return it through the FHIR API to the iPhone, we need to reassemble the address into two lines (two entries in the lines array) address-line-1 and address-line-2.

2016-10-11 08:14 UTC, Leo24 commented on src/Adapters/FHIRPatientAdapter.php
> +        $line->setValue($patient->getStreet());
Oh.
Now I understood. Thank you for detailed clarification.
Current functionality already returns array of street lines.
Do we need to add keys to address lines?
Like this 
"line": [
        [
          "address-line-1" : "Street Value 1",
          "address-line-2" : "Street Value 2"
        ]

![patient_adresses](https://cloud.githubusercontent.com/assets/5683856/19263128/73b620b8-8fa3-11e6-81c6-976b408680cc.png)

{
  "resourceType": "Patient",
  "extension": [
    {
      "extension": [
        {
          "valueString": "",
          "url": "#groupId"
        },
        {
          "valueString": "active",
          "url": "#status"
        },
        {
          "valueString": 34,
          "url": "#providerId"
        },
        {
          "valueString": 5,
          "url": "#pharmacyId"
        },
        {
          "valueString": "Some value of stripeToken",
          "url": "#stripeToken"
        }
      ],
      "url": "http://libre-emr.loc/fhir/extension/gponline-patient-data"
    }
  ],
  "identifier": [
    {
      "use": "usual",
      "value": 75
    }
  ],
  "name": [
    {
      "use": "usual",
      "family": [
        "Dow"
      ],
      "given": [
        "Judy Simple"
      ]
    }
  ],
  "telecom": [
    {
      "system": "phone",
      "value": "555-555-2003",
      "use": "primary"
    },
    {
      "system": "email",
      "value": "",
      "use": "primary"
    }
  ],
  "gender": "female",
  "birthDate": "1955-01-06",
  "address": [
    {
      "line": [
        [
          "address-line-1",
          "address-line-2"
        ]
      ],
      "city": "Sent-Petersburg",
      "district": "USA"
    }
  ]
}

2016-10-11 13:49 UTC, kchapple approved these changes

2016-10-11 13:49 UTC, kchapple commented on src/Adapters/FHIRPatientAdapter.php
> +        $line->setValue($patient->getStreet());
@Leo24 Your PostMan screenshot is correct.

2016-10-11 13:49 UTC, merged